### ISSUE TITLE
Multiple read Execio in a single script

### ISSUE THREAD

**Issue by Vittimj** [mvslovers/brexx370#106]
On MVS3.8J (Turnkey MVS) I am trying to have a REXX session running in a loop that will accept commands from a PL/I (F) program and pass the results back.  

The commands will include things like does this dataset exist, is that member in the LNKLST concatenation, provide dataset information).  

I thought the simplest solution was to have the PL/I program write a request to a file, then BREXX/370 (in a wait, read, exec, wait) loop read and process the request, writing the results back.

My initial testing shows that the second EXECIO causes a BREXX/370 abend, while the first one works perfectly well.  I saw some debugging code you provided elsewhere and incorporated that, into the below:
                                        
NOT_OK = 28                                                             
OK     = 0                                                                                                                                                       
 "EXECIO * DISKR PLAN (STEM xxxrec. finis"                        
If rc <> OK                                                             
Then Do                                                                 
   Say "EXECIO gave RC = "rc                                            
   Exit NOT_OK                                                          
End                                                                                  
say xxxrec.0 "records read"
do i = 1 to xxxrec.0
   say xxxrec.i
   end   

say "next execio"                                                                                                                                   
 "EXECIO * DISKR PLAN (STEM xxxrec. finis"                                                                                                         
If xxxrec.0 = 0                                                        
Then Do                                                                                                                     
   Say 'XXX001E: NO DATA RECORDS READ'                                 
   Return 16                                                                                                                                  
End                                                                                     
         
Exit  005                                                                 
 /*===================================================================*/
ohShit:                                                                
 /*-------------------------------------------------------------------*/
 /* Rexx Error routine. Called on Syntax error. Issue error details & */
 /* terminate the script with the return code.                        */
 /*-------------------------------------------------------------------*/
_errorrc = rc                                                          
Parse source . . _exec .                                               
Say 'An error has been encountered in '||_exec 
Say 'Return code is: ' _errorrc                             
Say 'The line of code in question is:' Sourceline(Sigl)'.'  
Say Errortext(_errorrc)                                     
Say ' '                                                     
Exit rc 
//EXEC.PLAN DD DSN=SYS3.EZRJCL.CONTROL(REXXPORT),DISP=SHR

the input jobstream, output pdf result and a screen shots of the control file are attached.  

I get the abend even when I use different DDnames, such as PLAN, PLAN1, PLAN2 (etc).  I could abandon this approach and have each script submit another version of its batch job (instead of having a wait loop), but this is a cleaner solution.

Any advice or thoughts?
 
![jclCapture](https://github.com/mvslovers/brexx370/assets/137300619/42610f8f-3679-452e-8696-dbbf17612683)
![outputCapture](https://github.com/mvslovers/brexx370/assets/137300619/44784f40-6fbc-4069-91cd-6e4f3da80631)
![abendCapture](https://github.com/mvslovers/brexx370/assets/137300619/f953ceb7-d643-45c3-a77a-82e4d64dc8c7)
![Capture](https://github.com/mvslovers/brexx370/assets/137300619/e36d7dd9-efa2-4dcc-9118-bac8041ecba2)
![codeCapture](https://github.com/mvslovers/brexx370/assets/137300619/5265de2c-87be-4531-8f49-1532f356e875)

**Comment by Peter-Jacob** [comment]
Which BREXX release are you running? Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Vittimj ***@***.***>Datum: Mi., 21. Juni 2023, 15:37An: mvslovers/brexx370 ***@***.***>Cc: Subscribed ***@***.***>Betreff: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)
On MVS3.8J (Turnkey MVS) I am trying to have a REXX session running in a loop that will accept commands from a PL/I (F) program and pass the results back.
The commands will include things like does this dataset exist, is that member in the LNKLST concatenation, provide dataset information).
I thought the simplest solution was to have the PL/I program write a request to a file, then BREXX/370 (in a wait, read, exec, wait) loop read and process the request, writing the results back.
My initial testing shows that the second EXECIO causes a BREXX/370 abend, while the first one works perfectly well.  I saw some debugging code you provided elsewhere and incorporated that, into the below:
NOT_OK = 28
OK     = 0
"EXECIO * DISKR PLAN (STEM xxxrec. finis"
If rc <> OK
Then Do
Say "EXECIO gave RC = "rc
Exit NOT_OK
End
say xxxrec.0 "records read"
do i = 1 to xxxrec.0
say xxxrec.i
end
say "next execio"
"EXECIO * DISKR PLAN (STEM xxxrec. finis"
If xxxrec.0 = 0
Then Do
Say 'XXX001E: NO DATA RECORDS READ'
Return 16
End
Exit  005
/===================================================================/
ohShit:
/-------------------------------------------------------------------/
/* Rexx Error routine. Called on Syntax error. Issue error details & /
/ terminate the script with the return code.                        /
/-------------------------------------------------------------------*/
_errorrc = rc
Parse source . . _exec .
Say 'An error has been encountered in '||_exec
Say 'Return code is: ' _errorrc
Say 'The line of code in question is:' Sourceline(Sigl)'.'
Say Errortext(_errorrc)
Say ' '
Exit rc
//EXEC.PLAN DD DSN=SYS3.EZRJCL.CONTROL(REXXPORT),DISP=SHR
the input jobstream, output pdf result and a screen shots of the control file are attached.
I get the abend even when I use different DDnames, such as PLAN, PLAN1, PLAN2 (etc).  I could abandon this approach and have each script submit another version of its batch job (instead of having a wait loop), but this is a cleaner solution.
Any advice or thoughts?

**Comment by Vittimj** [comment]
BREXX.V2R5M2

**Comment by Peter-Jacob** [comment]
I tried to reproduce your 0C4, without success. I even ran the loop 6 times:

```
1. EXECIO, RC=0, Lines read: 6     
6 records read                     
        THIS IS CARD 1             
        THIS IS CARD 2             
        THIS IS CARD 3             
        THIS IS CARD 4             
        THIS IS CARD 5             
        THIS IS THE LAST CARD      
next execio                        
1. EXECIO RC=0, Lines read: 6      
next execio                        
2. EXECIO RC=0, Lines read: 6      
next execio                        
3. EXECIO RC=0, Lines read: 6      
next execio                        
4. EXECIO RC=0, Lines read: 6      
next execio                        
5. EXECIO RC=0, Lines read: 6       
next execio                        
6. EXECIO RC=0, Lines read: 6
```       
The data are the ones you provided, aren't they?  What is the output format of the DSN, I used FB80

**Comment by Peter-Jacob** [comment]
this is my version of your rexx:
```
NOT_OK = 28                                        
OK = 0                                             
"EXECIO * DISKR PLAN (STEM xxxrec. finis"          
SAY "1. EXECIO, RC="rc", Lines read: "xxxrec.0     
If rc <> OK then do                                
   Say "EXECIO gave RC = "rc                       
   Exit NOT_OK                                     
End                                                
say xxxrec.0 "records read"                        
do i = 1 to xxxrec.0                               
   say xxxrec.i                                    
end                                                
do k=1 to 6                                        
   say "next execio"                               
  "EXECIO * DISKR PLAN (STEM xxxrec. finis"        
   SAY k'. EXECIO RC='rc', Lines read: 'xxxrec.0   
   If xxxrec.0 = 0 then do                         
      Say 'XXX001E: NO DATA RECORDS READ'          
      Return 16                                    
   End                                             
End                                                                   
Exit 005                                                              
/*=================================================================*/ 
ohShit:                                                               
/*-----------------------------------------------------------------*/ 
/* Rexx Error routine. Called on Syntax error. Issue error details &*/
/*terminate the script with the return code.*/                        
/*------------------------------------------------------------------*/
_errorrc = rc                                                         
Parse source . . _exec .                                              
Say 'An error has been encountered in '_exec                          
Say 'Return code is: ' _errorrc                                       
Say 'The line of code in question is:' Sourceline(Sigl)'.'            
Say Errortext(_errorrc)                                               
Say ' '                                                               
Exit rc       
```

**Comment by Peter-Jacob** [comment]
Just to clarify, my version also abended, didn't it? What is the DCB of your input dsn. If it abends, I will send you a version with more debugging content. -------- Ursprüngliche Nachricht --------Von: Vittimj ***@***.***>Datum: Do., 22. Juni 2023, 15:01An: mvslovers/brexx370 ***@***.***>Cc: Peter-Jacob ***@***.***>, Comment ***@***.***>Betreff: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)
Thank you.



 



I put *your code into my deck* (added a say version() to the top) and ran it with the same outcome (I’ve provided the job output).



 



So: rexx code is the same, data access is not a problem (shared member name) and I can print the file via IEBGENER after the rexx step; all that’s left is the execution environment. I’m using RXBATCH from the distribution library. (I’ve provided the JCL deck). After your email I tried RXTSO with the same result (it was a reach, but still).



 



I know the installation is OK, I just adopted the Rob Prins dasd ‘as is’. 



 



Job deck as submitted is the ‘.JCL file’ and the output is the ‘.PDF’.



 



Since BREXX can clearly perform multiple I/O for you, then I must conclude that either (1) I’m doing something wrong but not yet detected, or (2) your BREXX  behaves differently from mine. Money is on #1.  



 



I regret my waste of your time, and will attempt another approach to solve my problem. Last time I was this confused was when I started working in computers in 1975. 



 



Thanks.



 



From: Peter-Jacob ***@***.***> 

Sent: Thursday, June 22, 2023 3:35 AM

To: mvslovers/brexx370 ***@***.***>

Cc: Vittimj ***@***.***>; Author ***@***.***>

Subject: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)



 



this is my version of your rexx:



NOT_OK = 28                                        

OK = 0                                             

"EXECIO * DISKR PLAN (STEM xxxrec. finis"          

SAY "1. EXECIO, RC="rc", Lines read: "xxxrec.0     

If rc <> OK then do                                

   Say "EXECIO gave RC = "rc                       

   Exit NOT_OK                                     

End                                                

say xxxrec.0 "records read"                        

do i = 1 to xxxrec.0                               

   say xxxrec.i                                    

end                                                

do k=1 to 6                                        

   say "next execio"                               

  "EXECIO * DISKR PLAN (STEM xxxrec. finis"        

   SAY k'. EXECIO RC='rc', Lines read: 'xxxrec.0   

   If xxxrec.0 = 0 then do                         

      Say 'XXX001E: NO DATA RECORDS READ'          

      Return 16                                    

   End                                             

End                                                                   

Exit 005                                                              

/*=================================================================*/ 

ohShit:                                                               

/*-----------------------------------------------------------------*/ 

/* Rexx Error routine. Called on Syntax error. Issue error details &*/

/*terminate the script with the return code.*/                        

/*------------------------------------------------------------------*/

_errorrc = rc                                                         

Parse source . . _exec .                                              

Say 'An error has been encountered in '_exec                          

Say 'Return code is: ' _errorrc                                       

Say 'The line of code in question is:' Sourceline(Sigl)'.'            

Say Errortext(_errorrc)                                               

Say ' '                                                               

Exit rc

**Comment by Vittimj** [comment]
Yes, sir, your code abended too. That was your code submitted and in the output spool that were attachments in the previous email.

 

The dataset information for the input is: (image and dcb)

 



 

Dsorg=po,recfm=fb,lrecl=80,blksize=9440

 

>8)

**Comment by Peter-Jacob** [comment]
I'll prepare something, and you get a debug version by tomorrow. The input dataset producing the 0C4 is still: 
```
 THIS IS CARD 1             
 THIS IS CARD 2             
 THIS IS CARD 3             
 THIS IS CARD 4             
 THIS IS CARD 5             
 THIS IS THE LAST CARD   
```
meaning a normal text file, not a file containing binaries. Especially records containing x'00' may create problems.

**Comment by Vittimj** [comment]
Plain text, no binary characters.

 

Thank you.

**Comment by Peter-Jacob** [comment]
Please download the debug version from [https://github.com/mvslovers/brexx370/releases/tag/V2R5M2DEBUG]
1 unzip the FIX archive brexxv2r5m2fbg1..zip
/2 upload the xmit file
/3 run an XMIT receive on the uploaded dataset (see sample in the installation guide)
/4 copy BREXX, RX, and REXX into SYS2.LINKLIB (all other loadlib members are unchanged).
/5 run execio rexx
and send me the debug results.

**Comment by Peter-Jacob** [comment]
Here is the description of the BREXX Installation Guide. It covers the upload and XMIT unpacking step.  
```
Step 1	- Upload XMIT File
Use the appropriate upload facility of your terminal emulation. 
The file created during upload must have RECFM FB and LRECL 80. If the DCB does not match, the subsequent unpacking process fails.
Step 2	- Unpack XMIT File
Unpack the XMIT file with an appropriate JCL. If you don't have one you can use the following sample, just cut and paste it into one of your TK4- JCL libraries:
//BRXXREC JOB 'XMIT RECEIVE',CLASS=A,MSGCLASS=H                 
//* ------------------------------------------------------------
//* RECEIVE XMIT FILE AND CREATE DSN OR PDS                     
//* ------------------------------------------------------------
//RECV370  EXEC PGM=RECV370,REGION=8192K                            
//RECVLOG  DD SYSOUT=*                                              
//XMITIN   DD  DSN=HERC01.UPLOAD.XMIT,DISP=SHR             
//SYSPRINT DD SYSOUT=*                                              
//SYSUT1   DD DSN=&&XMIT2,                                          
//    UNIT=3390,                                                    
//    SPACE=(TRK,(300,60)),                                         
//    DISP=(NEW,DELETE,DELETE)                                      
//SYSUT2   DD DSN=BREXX.V2R5M2.INSTALL,                        
//    UNIT=3390,                                                    
//    SPACE=(TRK,(300,60,20)),                                      
//    DISP=(NEW,CATLG,CATLG)                                        
//SYSIN    DD DUMMY                                             
 
HERC01.UPLOAD.XMIT 	represents the uploaded XMIT File – please change it to the name you chose during the upload process. 
BREXX.V2R5M2.INSTALL	is the name of the unpacked library (created during the UNPACK process). It is recommendable to remain with this DSN as it is used in later processes  
Make sure there is no previous version of this PDS catalogued; 

```

**Comment by Vittimj** [comment]
All done. All steps completed without error.

Input job deck and output attached.

 

Happy Sunday! Thank you.

Mike Vitti

**Comment by Peter-Jacob** [comment]
Did you attach the output? You can also send me a dropbox or onedrive link.

**Comment by Vittimj** [comment]
I did, but am generally unfamiliar with Github, so I resend them now via a onedrive link

 

https://1drv.ms/f/s!Ak_4r1pHwG05jhSMm4tP7OKckCuz?e=djE36c

**Comment by Peter-Jacob** [comment]
0h, so the new version didn't abend? This looks as there was a corrupted Brexx load module-------- Ursprüngliche Nachricht --------Von: Vittimj ***@***.***>Datum: Mo., 26. Juni 2023, 12:51An: mvslovers/brexx370 ***@***.***>Cc: Peter-Jacob ***@***.***>, Comment ***@***.***>Betreff: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)
I did, but am generally unfamiliar with Github, so I resend them now via a onedrive link



 



https://1drv.ms/f/s!Ak_4r1pHwG05jhSMm4tP7OKckCuz?e=djE36c



 



 



 



From: Peter-Jacob ***@***.***> 

Sent: Monday, June 26, 2023 2:11 AM

To: mvslovers/brexx370 ***@***.***>

Cc: Vittimj ***@***.***>; Author ***@***.***>

Subject: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)



 



Did you attach the output? You can also send me a dropbox or onedrive link.

**Comment by Peter-Jacob** [comment]
I can also provide you with a fresh copy of the Brexx modules-------- Ursprüngliche Nachricht --------Von: Vittimj ***@***.***>Datum: Mo., 26. Juni 2023, 13:46An: mvslovers/brexx370 ***@***.***>Cc: Peter-Jacob ***@***.***>, Comment ***@***.***>Betreff: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)
I saved an image of the virtual machine and will rerun the test against the old software and load modules, it will of course abend as before.



 



Then I will re-down the rob prin distribution for the TK4 disks and compare a fresh copy of his load modules to those on my restored system. If both sets are identical, then I would conclude that there is a corruption in his distribution.  



 



As a final test I will download a fresh copy of the installation from your site, and now that understand the XMIT procedure I can obtain and upload a fresh distribution from you.  I would then do a file compare of every item in your distribution to what Rob has in his preinstalled V2R5M2, providing yet another data point.



 



After we get that far, one of us could contact him (however you may prefer).



 



Does that sound reasonable to you?



 



From: Peter-Jacob ***@***.***> 

Sent: Monday, June 26, 2023 7:37 AM

To: mvslovers/brexx370 ***@***.***>

Cc: Vittimj ***@***.***>; Author ***@***.***>

Subject: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106)



 



0h, so the new version didn't abend? This looks as there was a corrupted Brexx load module-------- Ursprüngliche Nachricht --------Von: Vittimj ***@***.***>Datum: Mo., 26. Juni 2023, 12:51An: mvslovers/brexx370 ***@***.***>Cc: Peter-Jacob ***@***.***>, Comment ***@***.***>Betreff: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106) 

I did, but am generally unfamiliar with Github, so I resend them now via a onedrive link 















https://1drv.ms/f/s!Ak_4r1pHwG05jhSMm4tP7OKckCuz?e=djE36c 































From: Peter-Jacob ***@***.***> 



Sent: Monday, June 26, 2023 2:11 AM 



To: mvslovers/brexx370 ***@***.***> 



Cc: Vittimj ***@***.***>; Author ***@***.***> 



Subject: Re: [mvslovers/brexx370] Multiple read Execio in a single script (Issue #106) 















Did you attach the output? You can also send me a dropbox or onedrive link.

**Comment by Vittimj** [comment]
Thank you. Please provide me a fresh copy and I will handle the comparison process with Mr. Prins distribution as per my previous notes, providing you with the results.

 

Then you can decide how to proceed.

 

It was a fun-frustrating experience, and I am now XMIT-Receive capable.

**Comment by Peter-Jacob** [comment]
Here is a link to the fresh BREXX load modules, please upload and process them accordingly:

https://1drv.ms/u/s!Ak38mWJOzl4ujbAUJN1wFDAlrKP6CA?e=HQn1iS

**Comment by Vittimj** [comment]
Thank you,

 

I processed the updates, and the program behaves correctly.  Thank you for your commitment to the software, diligence and expertise.

 

I will return to a fresh distribution from Mr. Prins website, reinstall and then ‘freshly’ check on the BREXX/370 behavior.  When I complete that, I’ll inform you of the result.

 

With respect, thank you again,
