### ISSUE TITLE
BREXX and HTTPD Server Testing

### ISSUE THREAD

**Issue by mikerayborn** [mvslovers/brexx370#119]
I've started work on integrating BREXX with the HTTPD server as a Common Gateway Interface (CGI) processor. For the most part it seems to be working well using temp datasets for STDOUT and STDERR and having the HTTPD server read those dataset and sending the lines read to the HTTPD clients.

While this "works" I can imagine this as inefficient for large output. A rexx script that creates a lot of output would seem to perform poorly because the HTTPD server has to read the output and then send it to the client. For small output sets the end user may not notice or care. But for scripts that are perhaps bridging between spooling products (think NJE/RJE type stuff) or say remote email servers, the output generated by the script could be very large.

It would be faster if we have a module that can be called from the BREXX script that would send output directly to the HTTPD client. And I've started work on a callable module to do just that.

But I have a problem with the way BREXX is currently handling external callable modules. When BREXX sees CALL module(...) it first attempts to fopen("current.pds.dataset(module)") since it first assumes that the named module is a script member in that PDS. And since the module name is NOT in the PDS the fopen() fails with MVS issuing:
IEC141I 013-18,IGG0191B,HTTPTEST,HTTPTEST,JCC00003,39A,MDRCAT,                                     
IEC141I MDR.HTTPD.BREXX
And every time a call is made to the module name you get the same IEC141I messages.

BREXX then seems to load/link the external module as expected. The external module does it's thing and returns control back to BREXX via standard return.

I would propose that either a different method is used to first see if the module name exist as a member, or perhaps try to locate the module name in the steplib/linklib datasets before proceeding as a script or external module from within BREXX.

Anyone who has a relationship with the BREXX developers should feel free to pass this along.
Thanks.
--Mike

**Comment by Peter-Jacob** [comment]
Hello Mike,

 

Moshe told me about the challenge you're taking on. I suppose there are areas which can be improved for your undertaking. 

Let’s start with: 

1.	>> I would propose that either a different method is used to first see if the module name exist as a member, or perhaps try to locate the module name in the steplib/linklib datasets before proceeding as a script or external module from within BREXX.

I can think of a BREXX command like this:

 

CALL OPTIONS ‘CALL-PRECEDENCE”,”STEPLIB”

 

It firstly looks at the library you want.  Would this help?  

 

2.	Data exchange between HTTP and BREXX

Instead of using temporary files, we could think about using a “storage communication area”. The problem is that we don’t have much storage available in MVS 3.8. We can actually address 6-8 MB if we run it standalone.

 

If you have any other ideas for improvements, just let me know. You can reach me directly at: ***@***.*** ***@***.***> .

 

Regards

 

Peter 

 

Von: mikerayborn ***@***.***> 
Gesendet: Montag, 6. Mai 2024 22:17
An: mvslovers/brexx370 ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mvslovers/brexx370] BREXX and HTTPD Server Testing (Issue #119)

 

I've started work on integrating BREXX with the HTTPD server as a Common Gateway Interface (CGI) processor. For the most part it seems to be working well using temp datasets for STDOUT and STDERR and having the HTTPD server read those dataset and sending the lines read to the HTTPD clients.

While this "works" I can imagine this as inefficient for large output. A rexx script that creates a lot of output would seem to perform poorly because the HTTPD server has to read the output and then send it to the client. For small output sets the end user may not notice or care. But for scripts that are perhaps bridging between spooling products (think NJE/RJE type stuff) or say remote email servers, the output generated by the script could be very large.

It would be faster if we have a module that can be called from the BREXX script that would send output directly to the HTTPD client. And I've started work on a callable module to do just that.

But I have a problem with the way BREXX is currently handling external callable modules. When BREXX sees CALL module(...) it first attempts to fopen("current.pds.dataset(module)") since it first assumes that the named module is a script member in that PDS. And since the module name is NOT in the PDS the fopen() fails with MVS issuing:
IEC141I 013-18,IGG0191B,HTTPTEST,HTTPTEST,JCC00003,39A,MDRCAT,
IEC141I MDR.HTTPD.BREXX
And every time a call is made to the module name you get the same IEC141I messages.

BREXX then seems to load/link the external module as expected. The external module does it's thing and returns control back to BREXX via standard return.

I would propose that either a different method is used to first see if the module name exist as a member, or perhaps try to locate the module name in the steplib/linklib datasets before proceeding as a script or external module from within BREXX.

Anyone who has a relationship with the BREXX developers should feel free to pass this along.
Thanks.
--Mike

**Comment by mikerayborn** [comment]
After reviewing some of the other methods in which I can call my external program, I've decided to make use of the ADDRESS LINKMVS command instead of the CALL command. It allows me to avoid any issues I reported above.

option 1) above, it might have helped but its probably not needed. I'll use LINKMVS.
option 2) above, probably not needed or worth the time given the limited memory we have in MVS 3.8

Thanks for looking into this for me.

**Comment by mgrossmann** [comment]
Please have in mind, that you could read and write REXX variables from within your external program, using the IRXEXCOM interface. (When needed)

best, Mike

**Comment by mikerayborn** [comment]
At the moment my needs are pretty simple. I'm just sending output back the my HTTPD server. Nothing fancy ;)


> Please have in mind, that you could read and write REXX variables from within your external program, using the IRXEXCOM interface. (When needed)
> 
> best, Mike
