### ISSUE TITLE
(stack - parse pull does not work on macOS

### ISSUE THREAD

**Issue by rvjansen** [mvslovers/brexx370#94]
➜  crexx_funxs git:(master) ✗ rexx nativedate.exec
     3 *-* "date (STACK"
[1]    53854 segmentation fault  rexx nativedate.exec

on Big Sur 11.4, M1
on X86_64, the parse pull hangs but does not segfault.

on brexx, both architectures, this works as designed.

**Comment by rvjansen** [comment]
trying to debug this:
     3 *-* "date (STACK"
Process 58341 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1efdfe310)
    frame #0: 0x0000000100019d54 brexx`IRXSTAM(pEnvBlock=0x0000000100206c08, pParms=0x00000001efdfe310) at hostenv.c:39:27
   36  	    LINITSTR(env)
   37  	    LINITSTR(cmd)
   38
-> 39  	    Lscpy2(&env,  pParms->envName, 8);
   40  	    Lscpy2(&cmd, *pParms->cmdString, *pParms->cmdLength);
   41
   42  	    Lstrip(&env, &env, LTRAILING, ' ');
Target 0: (brexx) stopped.
(lldb)

**Comment by rvjansen** [comment]
(lldb) var
(RX_ENVIRONMENT_BLK_PTR) pEnvBlock = 0x0000000100206c08
(RX_HOSTENV_PARAMS_PTR) pParms = 0x00000001efdfe310
(int) rc = 1
(Lstr) env = (pstr = 0x0000000000000000, len = 0, maxlen = 0, type = 0)
(Lstr) cmd = (pstr = 0x0000000000000000, len = 0, maxlen = 0, type = 0)

**Comment by mgrossmann** [comment]
Hi René,

I give it a fast try.


Is it just the `DATE (STACK` part? Or did you any `ADDRESS` stuff before?


/Mike

**Comment by mgrossmann** [comment]
René, other Question,

do you really use "our" brexx/370 on OS X?



/MIke

**Comment by mgrossmann** [comment]
BREXX/370 is currently not supporting stacking of the command output. This is because in MVS there are to many access method to write to the terminal. The other reason, MVS did not have the native STACK like VM did. We have some ideas, but they are all not part of the current V2R5 release train. But anyways, can you send me your test exec, please?


Best, Mike

**Comment by rvjansen** [comment]
this is the testcase:

nativedate:
trace 'r'
  "date (STACK"
parse pull outcome
say outcome
parse var outcome . mon dt . . yr
say mon
say dt
say yr
retval= dt mon yr
say retval

**Comment by rvjansen** [comment]
"do you really use "our" brexx/370 on OS X?"

yes, I thought I should start using that because of our plans with cRexx; also, because it has a CMakeLists which is a lot better than the current brexx build system. I was starting to make the IBM Rexx compatible date functions available, but apart from this command issue (which is non-blocking) I notice it also has the recursive invocation bug, which is blocking at the moment.

**Comment by mgrossmann** [comment]
Hey René,

I don't think, it will work this way. 
Problem 1) If you call "data (STACK" date will be executed in A host environment. 
```
 READY
repl                                         
 ### BREXX/370 V2R5M0.DEV (Jul 17 2021) ###  
                                             
 TYPE EXIT TO EXIT.                          
 BREXX                                       
say address()                                
 TSO                                         
 BREXX                                       
date                                         
 DATE = 07/21/21  (21.202)    TIME = 09.11.24
 BREXX                                       
address mvs                                  
 BREXX                                       
date                                         
 DATE     ENDED DUE TO ERROR+                
 READY                                       
?                                            
 SYSTEM ABEND CODE 0C4   REASON CODE 010     
 READY     
```

Currently there is no usable host environment outside MVS. May be we should have a ADDRESS SYSTEM in __CROSS__ only.
With that, the call for `date`should work. 

Problem 2) is the lack of a stack. In VM we could use the (STACK option on almost every command. That is not the case in MVS.
Peter and I already thought about using the TSO internal stack for such things. But it makes no sense, as long as the operating system commands do not support this. The other way to solve this, is the way we have chosen for the `outrap()` command. There we could capture output done by the PUTLINE assembler macro. 

But all this will not help with your problem on MacOS. We have to (re)implement the stack stuff like it was in the original stack. 
Because our focus was MVS/370 we did not care about those problems, yet. 

If such a feature would help you to improve Rexx development, we should talk about implementing missing things.



Regards,
Mike
